# GitHub 官方赞助
github: 777lijiaqi

# 自定义链接：这里直接指向你 README 中刚才建立的那个锚点
custom: ["https://github.com/777lijiaqi/UniQ-Embedded-Lib#sponsorship"]
custom: ["https://github.com/777lijiaqi/UniQ-Embedded-Lib#sponsorship-cn"]
